version: '3'
services:
  node-builder-web:
    image: node:18.17.0
    volumes:
      - ./:/var/www/html
    container_name: node-builder-web
    command: >
      bash -c "cd /var/www/html && yarn install && yarn build"

  build-source-admin:
    depends_on:
      - node-builder-web
    image: nginx
    ports:
      - '81:80'
    restart: always
    volumes:
      - ./config/nginx-custom.conf:/etc/nginx/conf.d/default.conf
      - ./config/mime.types:/etc/nginx/mime.types
      - ./dist:/usr/share/nginx/html
    container_name: build-source-admin
    networks:
      - build-source-admin

networks:
  build-source-admin:
    driver: bridge
