import { Box, List } from '@mui/material'
import { Fragment, useState } from 'react'
import { useNavigate } from 'react-router-dom'
// import { Settlement, Product, DigginLogo, Info, Notification, Artist, News, Payment, User } from '~/assets/imgs'
// import { PATH } from '~/constants/common'
// import { Typography } from '~/elements'
// import NavigateItem from './navigate-item/navigate-item'
// import styles from './sidebar.module.scss'
import { SidebarData } from './sidebar.type'
